### PR TITLE
Add English Translation

### PR DESCRIPTION
**Pull request by MrWillCom**
Add English translation to the site.

Mentioned in #7 .

### CODE REVIEW

**Comment by CLCK0622** [comment]
We finished proofreading.  
Now waiting for @MrWillCom to create pull request after final review.

**Comment by MrWillCom** [comment]
Sorry to be a bit late, now this pr is ready for review. 🚀

**Comment by timqian** [comment]
🎉🎉

**Comment by timqian** [comment]
We are now able to show HN this🐶: https://news.ycombinator.com/show

**Pull request merged**
